### PR TITLE
OpenCDC integration

### LINKED ISSUE #79: Bug: Deletions appear as empty messages
### Bug description

When objects are deleted from a S3 bucket, the source connector currently represents this as an empty message.

### Steps to reproduce

1. Create a S3 Bucket with versioning enabled
2. Create a conduit pipeline using the s3 source connector (using file destination for this test)
3. Create a file + destination file connector in the pipeline
4. `tail -f` the output file
5. Add a new file to the S3 bucket, see that it's reflected in the destination file
6. Delete the file, you should see a newline in the output
7. For posterity, add another file. It will be easier to see the empty newline message in between the two messages.

Example following all steps above:
```
❯ tail -f ~/output.txt
{
  "test": "test"
}

{
  "test": "test"
}
```
The newline in between the two messages correlated with the deletion of an S3 object.

### Version

connector = v0.1.1, conduit = Conduit v0.3.0-nightly.20220720-4-g6dacd3e darwin/amd64,

### PR DESCRIPTION
**Pull request by lovromazgon**
### Description

Updates SDK to the latest version and integrates OpenCDC record into the connector. I also took the opportunity to improve some things:
- CDC iterator is more efficient since it doesn't allocate a new cache slice every time it fetches metadata for S3 objects. It now allocates two slices when it starts running and switches between them (while one is being populated the other is used in `flush` to fetch object data and create records).
- Updated `TestSource_CDC_UpdateWithVersioning` (previously `TestSource_CDC_ReadRecordsUpdate`) to create a versioned bucket (updates are only detected in versioned buckets).
- Improved writing of parquet records so it happens in memory instead of by writing a temporary file.

Depends on https://github.com/ConduitIO/conduit-connector-sdk/pull/31 (needs to be merged and we need to update the connector SDK version).

Related to https://github.com/ConduitIO/conduit/issues/512.
Fixes #79.

### Quick checks:

- [X] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [X] There is no other [pull request](https://github.com/ConduitIO/conduit-connector-s3/pulls) for the same update/change.
- [X] I have written unit tests.
- [X] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

**Review by maha-hajja — APPROVED** [review]
lgtm

File: source/source_integration_test.go [hunk 1]
```diff
@@ -244,13 +244,23 @@ func TestSource_CDC_ReadRecordsInsert(t *testing.T) {
...
+func TestSource_CDC_UpdateWithVersioning(t *testing.T) {
 	client, cfg := prepareIntegrationTest(t)
 
 	ctx := context.Background()
 	testBucket := cfg[config.ConfigKeyAWSBucket]
 	source := &Source{}
-	err := source.Configure(context.Background(), cfg)
+
+	// make the bucket versioned
+	_, err := client.PutBucketVersioning(ctx, &s3.PutBucketVersioningInput{
```
Comment (hariso) [inline source/source_integration_test.go:255]: I assume this operation is idempotent, and won't fail if you try enabling versioning for a bucket which already has it enabled?

Comment (lovromazgon) [reply source/source_integration_test.go:255]: Based on the word "put" I expect it to be idempotent, but even if it's not, we create a new bucket for each test.
